# Site
name: "Tarot Happy"
title_suffix: "Tarot Happy | Tarot Guides"
title: ""
description: ""
meta_description: ""
logo: ''
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.tarothappy.com"
permalink: /:categories/:title
email: "contact@tarothappy.com"
google_analytics: ""

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams
    gravatar:
    email: ""
    description: ""
